language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shaggybb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaggybb/docker-react npm run test